package com.librarymanagement.project.models;


import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;


/**
 * Represents a Book entity in the library management system.
 * This entity stores information about books.
 */
@Entity
@Table(name = "books")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Book {

    /**
     * The unique identifier for the book.
     * This ID is automatically generated by the database when a new book is created.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "book_id")
    private Long bookId;


    /**
     * The title of the book.
     * This field cannot be blank.
     */
    @NotBlank
    @Column(name="title")
    private String title;

    /**
     * The author of the book.
     * This field cannot be blank.
     */
    @NotBlank
    @Column(name="author")
    private String author;

    /**
     * The total number of copies of this book available in the library.
     * This value represents all copies of the book, regardless of availability.
     */
    @Column(name="copies_total")
    private int copiesTotal;

    /**
     * The number of copies of the book that are currently available for borrowing.
     * This value is updated when books are borrowed or returned.
     */
    @Column(name = "copies_available")
    private int copiesAvailable;

    /**
     * A description of the book.
     */
    @Column(name="description")
    private String description;

    /**
     * The category to which this book belongs.
     * A book can belong to only one category, but each category can contain multiple books.
     */
    @ManyToOne
    @NonNull
    @JoinColumn(name = "category_id")
    private Category category;


    /**
     * Validates that the total number of copies is no less than the available copies.
     */
    @PrePersist
    @PreUpdate
    private void validateCopies() {
        if (this.copiesAvailable > this.copiesTotal) {
            throw new IllegalArgumentException("Total copies cannot be less than available copies");
        }
    }

    /**
     * Checks if the book is available for borrowing.
     *
     * @return true if there are copies available, false otherwise.
     */
    public boolean isAvailable(){
        return this.copiesAvailable > 0;
    }

    /**
     * Borrows one copy of the book.
     * It reduces the number of available copies by 1.
     */
    public void borrowOneCopy(){
        if(this.copiesAvailable > 0){
            this.copiesAvailable = this.copiesAvailable - 1;
        }
    }

    /**
     * Returns one copy of the book.
     * It increases the copies available by 1.
     */
    public void returnOneCopy() {
        if(this.copiesAvailable < this.copiesTotal) {
            this.copiesAvailable = this.copiesAvailable + 1;
        }
    }
}
