package com.librarymanagement.project.models;


import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
* Represents a Category entity in the library management system.
* This entity stores information about the category of books.
*/
@Entity
@Table (name = "categories", uniqueConstraints = {
        @UniqueConstraint(columnNames = "category_name")
    })
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Category {

    /**
    * Unique identifier for the category.
    * The value is automatically generated by the database.
    */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "category_id")
    private Long categoryId;

    /**
    * The name of the category.
    * This field cannot be blank, must contain at least 5 characters and must be unique
    * */
    @NotBlank
    @Size(min = 5, message = "Category name must contain at least 5 characters")
    @Column(name = "category_name", unique = true)
    private String categoryName;

}
