package com.librarymanagement.project.models;


import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * Represents a Role entity in the library management system.
 * Roles are used in role-based access control (RBAC) to assign specific permissions to users in the system.
 * This entity stores information about the role and its associated name.
 */
@Entity
@Table(name = "roles")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Role {

    /**
     * The unique identifier for each role.
     * The value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "role_id")
    private  Integer roleId;

    /**
     * The name of the role represented by the {@link AppRole} enum.
     * This field stores the role as a string (e.g., "ROLE_ADMIN", "ROLE_USER").
     */
    @ToString.Exclude
    @Enumerated(EnumType.STRING)
    @Column(name = "role_name")
    private AppRole roleName;

    /**
     * Constructor to create a new Role with a specified role name.
     *
     * @param roleName The name of the role, represented by the {@link AppRole} enum.
     */
    public Role(AppRole roleName){
        this.roleName = roleName;
    }
}
